### ISSUE TITLE
Bookmark toggle by single mouse click

### ISSUE THREAD

**Issue by CTimmerman** [atom/bookmarks#87] opened 2017-03-24 13:15 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can't toggle bookmark with single mouse click. MacBook Air requires multiple keypresses (fn+cmd+F2) instead. 

### Steps to Reproduce

1. Click next to line number, in bookmark area.

**Expected behavior:** Bookmark toggles.

**Actual behavior:** Line is selected.

**Reproduces how often:** 100%

### Versions

Atom 1.15.0

MacOS Sierra 10.12.3 (16D32)

### Additional Information

[Notepad++](https://notepad-plus-plus.org/) and [Geany](https://www.geany.org/) do have this feature.

**Comment by 50Wliu** [comment] 2017-03-24 15:25
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #10. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-03-24 15:25 UTC

**Comment by jonasflint** [comment] 2017-05-07 15:14
Why did you close this out?  I'm reading because it's a duplicate, but that one is closed out also. If you close both out, it doesn't get worked on....

**Comment by 50Wliu** [comment] 2017-05-07 15:33
@jonasflint I'm not sure what you're talking about.  #10 is still open.
