### ISSUE TITLE
Bookmarks stop working after adding 2 bookmark above the first.

### ISSUE THREAD

**Issue by irafunesta** [atom/bookmarks#78] opened 2016-12-06 11:57 UTC
Hello, i'm using the bookmark functionalities on Atom, and i have noticed a bug that is consistent. 
Step to reproduce 
- Open a file (no matter the extension)
- Add a bookmark with cmd+f2 (e.g at line 3)
- Add another one at line 4, now if you press f2, you can cycle through line 3-4
- Add a bookmark at line 2, now if you press f2, you can cycle through line 2-3-4
- Add a bookmark at line 1, now the cycle is broken, with f2 it always jump at the last inserted bookmarks, and with shift-f2 it jumps to the first

Expected 
Be able to jump through bookmarks 1-2-3-4 by pressing f2 and once reached the 4 jumps back to 1

I'm on MacOS Sierra 10.12.1, with Atom 1.12.6 and package 'bookmarks' 0.42.0

**Comment by Ben3eeE** [comment] 2016-12-06 12:04
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bookmarks/issues/69, which has been fixed in Atom 1.13.0. ✨ 

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2016-12-06 12:04 UTC
