### ISSUE TITLE
Using bookmarks:view-all to switch to an untitled (unsaved) file opens a new untitled file

### ISSUE THREAD

**Issue by babyman** [atom/bookmarks#38] opened 2015-09-08 23:00 UTC
Open a new untitled file and add a bookmark, then use the bookmarks:view-all keyboard shortcut and select the bookmark just added, this will open a new untitled file.

![image](https://cloud.githubusercontent.com/assets/120736/9749458/0992c420-565b-11e5-8387-c4ad640f199f.png)

Expected Result:

Cursor jumps to the bookmark in the correct untitled file

OS: OSX version 10.10.5 (14F27)
Atom Version: 1.0.11
Bookmarks Version: 0.36.0

Thanks for the great work, please let me know if you need any further details.

**Comment by 50Wliu** [comment] 2015-09-09 01:15
Confirmed on Windows 10, Atom 1.0.11.

**Comment by mateuspv** [comment] 2017-10-12 21:39
I could not reproduce this on latest version of atom:

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Linux

**Comment by rsese** [comment] 2017-10-12 22:06
Thanks @mateuspv :v:

I can't reproduce either with Atom `1.23.0-dev-bdfa61e84` on macOS 10.12.6.  Closing for now but if anyone can still reproduce, please let us know.

**Closed by rsese** 2017-10-12 22:06 UTC
Labels: bug
