### ISSUE TITLE
Bookmark is erased on line swap

### ISSUE THREAD

**Issue by dimitrik-fr** [atom/bookmarks#89] opened 2017-08-10 15:43 UTC
How to reproduce:
 - set a bookmark on a current line with CMD-F2
 - stay on the line and swap it up or down with Ctrl-CMD-Up or Ctrl-CMD-Down
 - bookmark will disappear.. 
 
(shortcuts are provided for Mac)

Rgds,
-Dimitri

**Comment by rsese** [comment] 2017-08-11 03:46
Thanks for reaching out!

In addition to filling out the template, I think this is basically a duplicate of https://github.com/atom/bookmarks/issues/28 so you can subscribe there for updates if you'd like.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Closed by rsese** 2017-08-11 03:46 UTC
