### ISSUE TITLE
Going to a bookmark from View All should search in all panes

### ISSUE THREAD

**Issue by acontreras89** [atom/bookmarks#35] opened 2015-07-22 00:23 UTC
When using `Bookmarks: View All`, the key-binding `enter` (or `shift-enter` as `fuzzy-finder` does) should look for the item in all panes instead of opening it in the active one.

**Comment by acontreras89** [comment] 2015-07-26 23:28
Just created atom/bookmarks#36 to add this enhancement.

**Comment by mliq** [comment] 2016-06-07 21:20
Clicking a bookmark in another tab does not navigate there - is this a regression?

**Comment by solendil** [comment] 2016-06-12 21:17
I confirm clicking a bookmark does not navigate there.

**Comment by Ben3eeE** [comment] 2016-10-30 13:50
Closing this since it looks like it was fixed by #36 and again by #65

**Closed by Ben3eeE** 2016-10-30 13:50 UTC
Labels: enhancement
