### ISSUE TITLE
Bookmarks extend over multiple lines when adding new lines

### ISSUE THREAD

**Issue by Tomasito665** [atom/bookmarks#84] opened 2017-01-28 15:29 UTC
### Description

When pressing enter on a bookmarked line, the bookmark extends over the new line, also rendering an extra bookmark icon. 

![Imgur](http://i.imgur.com/fthyQIV.gif)

### Steps to Reproduce

1. Create a bookmark on the current line with the `bookmarks:toggle-bookmark` command.
2. Press `Enter` to create a new line.
3. Either press `Enter` again or place any character on the current line so that the line isn't empty.

**Expected behavior:** 
I wouldn't expect the bookmark to extend over the new line.

**Actual behavior:** 
It extends over the new line and also renders a new bookmark icon.

**Reproduces how often:**
As far as I know, always.

### Versions
```
> atom --version

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
> npm --version

3.10.10
```

**bookmarks** This issue happens both on version `0.43.2` and `0.44.0` of bookmarks. 
**OS** Windows 10 Version 1607

**Additional info**
I used this to boot Atom `atom --safe --clear-window-state`.

**Comment by Ben3eeE** [comment] 2017-08-08 10:53
This looks like the issue that was fixed in https://github.com/atom/bookmarks/pull/72 and I am unable to reproduce using Atom 1.19.0-beta7. Please let us know if you still see this issue in the latest version of Atom and we can reopen.

**Closed by Ben3eeE** 2017-08-08 10:53 UTC
