### ISSUE TITLE
Add a way to bookmark all search results

### ISSUE THREAD

**Issue by aharpervc** [atom/bookmarks#41] opened 2015-09-16 17:38 UTC
I don't see any way this is possible right now...

**Comment by sobi3ch** [comment] 2016-02-09 14:58
+1

**Comment by Ben3eeE** [comment] 2016-10-30 13:59
This is a duplicate of https://github.com/atom/bookmarks/issues/13. Feel free to subscribe there for updates.

**Closed by Ben3eeE** 2016-10-30 13:59 UTC
Labels: enhancement, package-idea
