### ISSUE TITLE
Feature request: click to bookmark

### ISSUE THREAD

**Issue by Zorgatone** [atom/bookmarks#48] opened 2016-01-22 09:34 UTC
Could you consider adding a way to make bookmarks clicking the line number (or right-click -> bookmark)?

The shortcuts vary on different OS and may be overwritten by package key conflicts (ex: https://github.com/TypeStrong/atom-typescript see issue https://github.com/TypeStrong/atom-typescript/issues/822).

I also think that the default bookmark icon is too small and is hard to see. I also think there should be a list of bookmarks of the current file in the status-bar, possibly.

Both the click-to-bookmark and the bookmark-list in the status-bar functionality I am thinking of resembles what any other IDE would do to add/show breakpoints

**Comment by 50Wliu** [comment] 2016-01-22 12:30
This is a duplicate of #10 - please subscribe there for updates.

**Closed by 50Wliu** 2016-01-22 12:30 UTC
