### ISSUE TITLE
Bookmarks lost after saving and closing file

### ISSUE THREAD

**Issue by rainbowtiger** [atom/bookmarks#97] opened 2018-02-11 14:23 UTC
After adding bookmarks to a file, then saving, then closing the file, bookmarks are gone the next time I open that file. I've tried in safe mode, same story. This happens every time, on all file types.

Steps to reproduce:

1. Add bookmarks to a file.
2. Save it then close it.
3. Reopen the file and the bookmarks are gone.

I tried package cop, turned off ALL packages, then tested, and bookmarks still get get lost after saving. Package cop says the package "Atom" is the cause.

Using Atom 1.23.1 on Mac OS 10.12.4.

**Comment by rsese** [comment] 2018-02-12 22:42
Thanks for moving this over @rainbowtiger - I searched through past issue and it looks like this has been reported here already:

https://github.com/atom/bookmarks/issues/61

So it sounds like if you quit and restart Atom the bookmarks will be retained (I verified this is the case on macOS 10.12.6 with Atom 1.23.3), but not if you close and reopen a file.  I'll go ahead and close this as a duplicate of https://github.com/atom/bookmarks/issues/61 and you can subscribe there for updates if you'd like.

**Closed by rsese** 2018-02-12 22:42 UTC

**Comment by rainbowtiger** [comment] 2018-02-12 22:47
OK, that explains the problem. Hope it gets fixed soon!
